## Sensor Data Normalization (Min-Max Scaling)
**Scenario**: You have an array of raw sensor readings and need to scale all values to a range between 0 and 1.

**Task**: Write a function that takes a 1D array of numbers and scales them using the formula:

$$\text{scaled} = \frac{x - x_{\min}}{x_{\max} - x_{\min}}$$


In [1]:

import numpy as np
from numpy.typing import NDArray


def min_max_normalize(data: NDArray[np.float32]) -> NDArray[np.float32]:
    min_v = np.min(data)
    max_v = np.max(data)

    return (data - min_v) / delta if (delta := max_v - min_v) != 0 else np.zeros_like(data)




In [2]:
min_max_normalize(np.array([1., 2., 3., 4.]))

array([0.        , 0.33333333, 0.66666667, 1.        ])

---


## Moving Average Smoothing
**Scenario**: A time-series of temperature measurements contains high-frequency noise. You need to smooth the curve using a rolling window of size 3.

**Task**: Use np.convolve to compute a moving average. Ensure the output length matches the input or handles boundaries cleanly (using the 'valid' mode).

In [5]:
def moving_average(data: NDArray[np.float32], sliding_window: int = 3) -> NDArray[np.float32]:
    sec = np.ones(sliding_window) / sliding_window
    return np.convolve(data, sec, mode='valid')


temperatures = np.array([20.1, 20.5, 21.0, 22.2, 21.8, 22.5, 23.0])
moving_average(temperatures)



array([20.53333333, 21.23333333, 21.66666667, 22.16666667, 22.43333333])

---

## Outlier Filtering via Z-Scores
**Scenario**: You need to clean a dataset by removing values that deviate significantly from the mean.

**Task**: Compute the Z-score for each element in an array (how many standard deviations away from the mean it is) and return a boolean mask for elements where the absolute Z-score is less than or equal to 2.



In [35]:
def filter_outliers(data: NDArray[np.float32], threshold=2.0) -> NDArray[np.bool_]:
    mean = np.mean(data)
    std = np.std(data)

    if std == 0:
        return np.zeros_like(data, dtype=np.bool_)
    z_scores = (data - mean) / std
    return np.abs(z_scores) <= threshold


measurements = np.array([10.2, 9.8, 10.1, 25.5, 10.3, 9.9, -5.0])
mask = filter_outliers(measurements, threshold=2.0)

measurements[mask]



array([10.2,  9.8, 10.1, 25.5, 10.3,  9.9, -5. ])